### ISSUE TITLE
make optionnal loglevel change for docker

### ISSUE THREAD

**Issue by talset** [redhat-cip/rcip-openshift-ansible#45]
Do we really need to fix this line ?
We should keep the default loglevel (info) and override if needed

```
- name: loglevel docker

  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: '^OPTIONS=.*'
    line: "OPTIONS='{{ docker_options }}'"
  notify:
      - restart docker
```
